force-app/main/default/objects/Animal_Shelter_Settings__c/Animal_Shelter_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>[Animal Shelter] Global settings for the Animal Shelter Starter Pack</description>
    <label>Animal Shelter Settings</label>
</CustomObject>

force-app/main/default/objects/Animal_Shelter_Settings__c/fields/Breeds_Migration_Complete__c.field-meta.xml
<CustomField>
    <fullName>Breeds_Migration_Complete__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates that the migration to the Breeds object has been completed.</description>
    <label>Breeds Migration Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal_Shelter_Settings__c/fields/Default_Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>Default_Animal_Name__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[Animal Shelter] Set this option if you want create a Animal Name automatically based on the Record Name.</description>
    <inlineHelpText>Set this option if you want create a Animal Name automatically based on the Record Name.</inlineHelpText>
    <label>Default Animal Name</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal_Shelter_Settings__c/fields/Default_Animal_Name_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Default_Animal_Name_Prefix__c</fullName>
    <description>[Animal Shelter] Set a prefix for the Animal Name if using the default animal name creation, i.e. Site name</description>
    <inlineHelpText>Set a prefix for the Animal Name if using the default animal name creation, i.e. Site name</inlineHelpText>
    <label>Default Animal Name Prefix</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Shelter_Settings__c/fields/Disable_Behaviour_Update__c.field-meta.xml
<CustomField>
    <fullName>Disable_Behaviour_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[Animal Shelter] By default when animal behaviours are updated on an assessment record the animal record is updated to reflect the new statuses.  Checking this setting disables the default behaviour</description>
    <label>Disable Behaviour Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal_Shelter_Settings__c/fields/Enable_Auto_Match__c.field-meta.xml
<CustomField>
    <fullName>Enable_Auto_Match__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Enables the Adoption auto match functions</description>
    <label>Enable Auto Match</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal_Shelter_Settings__c/fields/microchip_api_Token__c.field-meta.xml
<CustomField>
    <fullName>microchip_api_Token__c</fullName>
    <label>Microchip API Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Shelter_Settings__c/fields/What3Words_API_Key__c.field-meta.xml
<CustomField>
    <fullName>What3Words_API_Key__c</fullName>
    <description>[Animal Shelter] API Key for What3Word integration</description>
    <inlineHelpText>API Key for What3Word integration</inlineHelpText>
    <label>What3Words API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AnimalShelterGetCustomSettings.cls
public with sharing class AnimalShelterGetCustomSettings {

    @AuraEnabled(cacheable=true) 
    public static %%%NAMESPACED_ORG%%%Animal_Shelter_Settings__c getCustomSettings(){
        return %%%NAMESPACED_ORG%%%Animal_Shelter_Settings__c.getOrgDefaults();
    }

    @AuraEnabled
    public static void saveCustomSetting(%%%NAMESPACED_ORG%%%Animal_Shelter_Settings__c customSetting) {
        update customSetting;
    }

    @AuraEnabled
    public static %%%NAMESPACED_ORG%%%Animal_Shelter_Settings__c createDefaultSettings() {
        %%%NAMESPACED_ORG%%%Animal_Shelter_Settings__c animal_settings = new %%%NAMESPACED_ORG%%%Animal_Shelter_Settings__c();
        animal_settings.%%%NAMESPACED_ORG%%%Breeds_Migration_Complete__c = true; 
        animal_settings.%%%NAMESPACED_ORG%%%Enable_Auto_Match__c = true;
        animal_settings.%%%NAMESPACED_ORG%%%Default_Animal_Name__c = true;
        animal_settings.%%%NAMESPACED_ORG%%%Disable_Behaviour_Update__c = false;
        animal_settings.%%%NAMESPACED_ORG%%%Default_Animal_Name_Prefix__c = '';
        animal_settings.%%%NAMESPACED_ORG%%%What3Words_API_Key__c = '';
        animal_settings.%%%NAMESPACED_ORG%%%microchip_api_Token__c = '';

        Database.SaveResult sr = Database.insert(animal_settings, false);
        if (sr.isSuccess()) {
            // Insert successful
            return animal_settings;
        } else {
            // Insert failed
            String errMsg = sr.getErrors()[0].getMessage();
            System.debug('Error message: ' + errMsg);
            throw new AuraHandledException('Error creating default settings: ' + errMsg);
        }
    }
}