force-app/main/default/objects/Animal_Shelter_Settings__c/Animal_Shelter_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>[Animal Shelter] Global settings for the Animal Shelter Starter Pack</description>
    <label>Animal Shelter Settings</label>
</CustomObject>

force-app/main/default/objects/Animal_Shelter_Settings__c/fields/Breeds_Migration_Complete__c.field-meta.xml
<CustomField>
    <fullName>Breeds_Migration_Complete__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates that the migration to the Breeds object has been completed.</description>
    <label>Breeds Migration Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal_Shelter_Settings__c/fields/Default_Animal_Name__c.field-meta.xml
<CustomField>
    <fullName>Default_Animal_Name__c</fullName>
    <defaultValue>false</defaultValue>
    <description>[Animal Shelter] Set this option if you want create a Animal Name automatically based on the Record Name.</description>
    <inlineHelpText>Set this option if you want create a Animal Name automatically based on the Record Name.</inlineHelpText>
    <label>Default Animal Name</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal_Shelter_Settings__c/fields/Default_Animal_Name_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Default_Animal_Name_Prefix__c</fullName>
    <description>[Animal Shelter] Set a prefix for the Animal Name if using the default animal name creation, i.e. Site name</description>
    <inlineHelpText>Set a prefix for the Animal Name if using the default animal name creation, i.e. Site name</inlineHelpText>
    <label>Default Animal Name Prefix</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal_Shelter_Settings__c/fields/Enable_Auto_Match__c.field-meta.xml
<CustomField>
    <fullName>Enable_Auto_Match__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Enables the Adoption auto match functions</description>
    <label>Enable Auto Match</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Animal_Shelter_Settings__c/fields/microchip_api_Token__c.field-meta.xml
<CustomField>
    <fullName>microchip_api_Token__c</fullName>
    <label>Microchip API Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AnimalShelterGetCustomSettingsTest.cls
/**
 * @description       :
 * @author            : Stewart Anderson
 * @group             :
 * @last modified on  : 10-17-2023
 * @last modified by  : Stewart Anderson
**/
@IsTest
private class AnimalShelterGetCustomSettingsTest {

    @IsTest static void testGetCustomSetting() {
        // Create a new custom setting record
        %%%NAMESPACED_ORG%%%Animal_Shelter_Settings__c setting = new %%%NAMESPACED_ORG%%%Animal_Shelter_Settings__c();
        setting.%%%NAMESPACED_ORG%%%Breeds_Migration_Complete__c = True;
        setting.%%%NAMESPACED_ORG%%%Default_Animal_Name__c = False;
        setting.%%%NAMESPACED_ORG%%%Default_Animal_Name_Prefix__c = 'pre';
        setting.%%%NAMESPACED_ORG%%%microchip_api_Token__c = 'TestValue';
        insert setting;

        // Call the getCustomSetting method and verify that the returned value matches the expected value
        %%%NAMESPACED_ORG%%%Animal_Shelter_Settings__c returnedSetting = AnimalShelterGetCustomSettings.getCustomSettings();
        System.assertEquals(setting.%%%NAMESPACED_ORG%%%microchip_api_Token__c, returnedSetting.%%%NAMESPACED_ORG%%%microchip_api_Token__c);
    }

    @IsTest static void testSaveCustomSetting() {
        // Create a new custom setting record
        %%%NAMESPACED_ORG%%%Animal_Shelter_Settings__c setting = new %%%NAMESPACED_ORG%%%Animal_Shelter_Settings__c();
        setting.%%%NAMESPACED_ORG%%%Breeds_Migration_Complete__c = True;
        setting.%%%NAMESPACED_ORG%%%Default_Animal_Name__c = False;
        setting.%%%NAMESPACED_ORG%%%Default_Animal_Name_Prefix__c = 'pre';
        setting.%%%NAMESPACED_ORG%%%microchip_api_Token__c = 'TestValueNew';
        insert setting;

        // Call the saveCustomSetting method with a new value and verify that the custom setting is updated
        String newValue = 'New Test Value';
        setting.%%%NAMESPACED_ORG%%%microchip_api_Token__c = newValue;
        AnimalShelterGetCustomSettings.saveCustomSetting(setting);
        %%%NAMESPACED_ORG%%%Animal_Shelter_Settings__c updatedSetting = [SELECT %%%NAMESPACED_ORG%%%microchip_api_Token__c FROM %%%NAMESPACED_ORG%%%Animal_Shelter_Settings__c WHERE Id = :setting.Id];
        System.assertEquals(newValue, updatedSetting.%%%NAMESPACED_ORG%%%microchip_api_Token__c);
    }

    @IsTest static void testcreateDefaultSettings(){
        AnimalShelterGetCustomSettings.createDefaultSettings();
        %%%NAMESPACED_ORG%%%Animal_Shelter_Settings__c returnedSetting = AnimalShelterGetCustomSettings.getCustomSettings();
        System.assertEquals(true, returnedSetting.%%%NAMESPACED_ORG%%%Enable_Auto_Match__c);
    }



}