packaged/objects/Animal__c.object
<CustomObject>
    <description>[Animal Shelter Starter] The core object in the Animal Shelter Starter which stores the details about an animal.</description>
    <fields>
        <fullName>Animal_Name__c</fullName>
        <inlineHelpText>Name of the animal</inlineHelpText>
        <label>Name</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Arrival__c</fullName>
        <inlineHelpText>Date and time which the animal arrived at the shelter</inlineHelpText>
        <label>Date of Arrival</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>The type of animal e.g. Dog</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Animal_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Animal</label>
    <nameField>
        <displayFormat>ANIMAL{00000}</displayFormat>
        <label>Animal Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/IsCloned__c.field-meta.xml
<CustomField>
    <fullName>IsCloned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCloned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Animal_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bird</fullName>
    </customValue>
    <customValue>
        <fullName>Cat</fullName>
    </customValue>
    <customValue>
        <fullName>Dog</fullName>
    </customValue>
    <customValue>
        <fullName>Donkey</fullName>
    </customValue>
    <customValue>
        <fullName>Horse</fullName>
    </customValue>
    <customValue>
        <fullName>Guinea Pig</fullName>
    </customValue>
    <customValue>
        <fullName>Hamster</fullName>
    </customValue>
    <customValue>
        <fullName>Hedgehog</fullName>
    </customValue>
    <customValue>
        <fullName>Ferret</fullName>
    </customValue>
    <customValue>
        <fullName>Gerbil</fullName>
    </customValue>
    <customValue>
        <fullName>Goat</fullName>
    </customValue>
    <customValue>
        <fullName>Mouse</fullName>
    </customValue>
    <customValue>
        <fullName>Pig</fullName>
    </customValue>
    <customValue>
        <fullName>Rabbit</fullName>
    </customValue>
    <customValue>
        <fullName>Pony</fullName>
    </customValue>
    <customValue>
        <fullName>Rat</fullName>
    </customValue>
    <customValue>
        <fullName>Fish</fullName>
        <isActive>false</isActive>
        <label>Fish</label>
    </customValue>
    <customValue>
        <fullName>Reptile</fullName>
        <isActive>false</isActive>
        <label>Reptile</label>
    </customValue>
    <description>[Animal Shelter] Types of Animals - not used post version 1.12</description>
    <masterLabel>Animal Type (Legacy)</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSCAnimalCloneDatatableControllerTest.cls
@isTest
public class FSCAnimalCloneDatatableControllerTest {
    
    @TestSetup
    static void setupTestData(){
        
        Animal__c testAnimal = new Animal__c(Animal_Name__c = 'Tandy', Type__c = 'Rabbit', Date_of_Arrival__c = Date.today(), IsCloned__c = True);
        Insert testAnimal;
    }   
    
    @isTest static void testReadRecord(){
        
	    List<Animal__c> tstRecord = new List<Animal__c>();
        tstRecord = FSCAnimalCloneDatatableController.getClonedAnimals();
        System.assertEquals(true,tstRecord.size()>0,'Read Animal Record Failed');
        
    }
    
    @isTest static  void testUpdateRecord(){
        
		List<Animal__c> tstUpdate = new List<Animal__c>();
        List<Animal__c> updateAnimal = [SELECT Animal_Name__c, Type__c, Date_of_Arrival__c FROM Animal__c WHERE IsCloned__c = True];
        List<SObject> aniUp = new List<SObject>();
        for(Animal__c a : updateAnimal){
            a.Animal_Name__c = 'Tommy';
            aniUp.add(a);
        }
        tstUpdate = FSCAnimalCloneDatatableController.updateClonedRecords(updateAnimal);
        System.assertEquals(tstUpdate.get(0).Animal_Name__c, 'Tommy','Animal name !="Tommy"');
    
    }
}