packaged/objects/Animal__c.object
<CustomObject>
    <description>[Animal Shelter Starter] The core object in the Animal Shelter Starter which stores the details about an animal.</description>
    <fields>
        <fullName>Animal_Name__c</fullName>
        <inlineHelpText>Name of the animal</inlineHelpText>
        <label>Name</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>The type of animal e.g. Dog</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Animal_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Animal</label>
    <nameField>
        <displayFormat>ANIMAL{00000}</displayFormat>
        <label>Animal Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Animal_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bird</fullName>
    </customValue>
    <customValue>
        <fullName>Cat</fullName>
    </customValue>
    <customValue>
        <fullName>Dog</fullName>
    </customValue>
    <customValue>
        <fullName>Donkey</fullName>
    </customValue>
    <customValue>
        <fullName>Horse</fullName>
    </customValue>
    <customValue>
        <fullName>Guinea Pig</fullName>
    </customValue>
    <customValue>
        <fullName>Hamster</fullName>
    </customValue>
    <customValue>
        <fullName>Hedgehog</fullName>
    </customValue>
    <customValue>
        <fullName>Ferret</fullName>
    </customValue>
    <customValue>
        <fullName>Gerbil</fullName>
    </customValue>
    <customValue>
        <fullName>Goat</fullName>
    </customValue>
    <customValue>
        <fullName>Mouse</fullName>
    </customValue>
    <customValue>
        <fullName>Pig</fullName>
    </customValue>
    <customValue>
        <fullName>Rabbit</fullName>
    </customValue>
    <customValue>
        <fullName>Pony</fullName>
    </customValue>
    <customValue>
        <fullName>Rat</fullName>
    </customValue>
    <customValue>
        <fullName>Fish</fullName>
        <isActive>false</isActive>
        <label>Fish</label>
    </customValue>
    <customValue>
        <fullName>Reptile</fullName>
        <isActive>false</isActive>
        <label>Reptile</label>
    </customValue>
    <description>[Animal Shelter] Types of Animals - not used post version 1.12</description>
    <masterLabel>Animal Type (Legacy)</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ReusableLocationTest.cls
@isTest
public class ReusableLocationTest {

    @isTest static void testLocation() {

        String tstObj = 'Animal__c';
        String tstName = 'Animal_Name__c';
        String tstLat = 'Geolocation__latitude__s';
        String tstLong = 'Geolocation__longitude__s';
        String tstText = 'Type__c';
        String tstDate = 'Entry_Date__c';
        
        Animal__c testAnimal = new Animal__c(Animal_Name__c = 'Tandy', Geolocation__latitude__s = 50.826425, Geolocation__longitude__s = -0.403983, Type__c = 'Rabbit', Entry_Date__c = Date.today());
        Insert testAnimal;
        
        List<Location> testingLocation = ReusableLocation.getLocation(tstObj, tstLat, tstLong, tstName, tstText, tstDate);


        

    }
}