packaged/objects/Animal__c.object
<CustomObject>
    <description>[Animal Shelter Starter] The core object in the Animal Shelter Starter which stores the details about an animal.</description>
    <fields>
        <fullName>Date_of_Arrival__c</fullName>
        <inlineHelpText>Date and time which the animal arrived at the shelter</inlineHelpText>
        <label>Date of Arrival</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Animal</label>
    <nameField>
        <displayFormat>ANIMAL{00000}</displayFormat>
        <label>Animal Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/what3words__c.field-meta.xml
<CustomField>
    <fullName>what3words__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Enter a what3words phase in the format word.word.word. Note the location may not appear immediately on saving the record</inlineHelpText>
    <label>what3words</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/W3WInvocableCalloutTest.cls
@isTest
private class W3WInvocableCalloutTest {
     @isTest static void testCallout() {

        Test.setMock(HttpCalloutMock.class, new MockW3WResponseGenerator());

        Animal__c theAnimal = new Animal__c(Date_of_Arrival__c = Date.Today(), what3words__c = 'whips.vanish.store');
        insert theAnimal;

        List<Animal__c> animals = new List<Animal__c>();
        animals.add(theAnimal);

        test.startTest();
            W3WInvocableCallout.getW3WCoordinates(animals);
        test.stopTest();
    }
}