packaged/objects/Animal__c.object
<CustomObject>
    <description>[Animal Shelter Starter] The core object in the Animal Shelter Starter which stores the details about an animal.</description>
    <label>Animal</label>
    <nameField>
        <displayFormat>ANIMAL{00000}</displayFormat>
        <label>Animal Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

packaged/objects/Animal_Alert__c.object
<CustomObject>
    <description>[Animal Shelter Starter] Records alerts or warnings against an Animal</description>
    <fields>
        <fullName>Alert_Message__c</fullName>
        <label>Alert Message</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Animal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Animal</label>
        <referenceTo>Animal__c</referenceTo>
        <relationshipLabel>Animal Alerts</relationshipLabel>
        <relationshipName>Animal_Alerts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <inlineHelpText>When will the alert stop showing on the record.</inlineHelpText>
        <label>End Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <inlineHelpText>The start date and time which the alert is active from.</inlineHelpText>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <label>Animal Alert</label>
    <nameField>
        <displayFormat>ALERT{00000}</displayFormat>
        <label>Animal Alert ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

packaged/classes/AlertBannerController.cls
/**
 * @File Name          : AlertBannerController.cls
 * @Description        : Controller for use with Animal Alert Lightning Component
 * @Author             : Stewart Anderson
 * @Group              : Salesforce.org
 * @Last Modified By   : Stewart Anderson (Salesforce.org)
 * @Last Modified On   : 4/7/2020, 8:50:48 AM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    4/6/2020   Stewart Anderson     Initial Version
**/
public with sharing class AlertBannerController {
   
    /**
    * @description Returns a list of related Animal Alerts for a given Animal record ID
    * @author Stewart Anderson (Salesforce.org) | 4/7/2020 
    * @param parentId 
    * @return List<Animal_Alert__c> 
    **/
    @AuraEnabled
    public static List<Animal_Alert__c> getRelatedAlertRecords(Id parentId) {
        if(parentId != null){
            List<Animal_Alert__c> AlertList = [SELECT Id, Alert_Message__c,Start_Date_Time__c,End_Date_Time__c FROM Animal_Alert__c WHERE Animal__c = :parentId AND Start_Date_Time__c <= TODAY AND (End_Date_Time__c >= TODAY OR End_Date_Time__c = NULL) LIMIT 20];
            return AlertList;
        } else {
            return null;
        }
    }
}