packaged/objects/Animal__c.object
<CustomObject>
    <description>[Animal Shelter Starter] The core object in the Animal Shelter Starter which stores the details about an animal.</description>
    <label>Animal</label>
    <nameField>
        <displayFormat>ANIMAL{00000}</displayFormat>
        <label>Animal Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

packaged/objects/Animal_Action__c.object
<CustomObject>
    <description>[Animal Shelter Starter] Used to capture scheduled actions against an animal</description>
    <fields>
        <fullName>Action_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Action Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Animal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Animal</label>
        <referenceTo>Animal__c</referenceTo>
        <relationshipLabel>Animal Actions</relationshipLabel>
        <relationshipName>Animal_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Time_of_Action__c</fullName>
        <inlineHelpText>The date &amp; time of when the action happened or when it should take place</inlineHelpText>
        <label>Date/Time of Action</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>The description of the action</inlineHelpText>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Animal Action</label>
    <nameField>
        <displayFormat>ACTION{00000}</displayFormat>
        <label>Animal Action Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animal Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

packaged/classes/AnimalActionRLClass2.cls
/**
 * @File Name          : AnimalActionRLClass2.apxc
 * @Description        : 
 * @Author             : Chris Rolfe (Salesforce.org)
 * @Group              : 
 * @Last Modified By   : Chris Rolfe (Salesforce.org)
 * @Last Modified On   : 4/30/2020, 5:18:43 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    4/30/2020   Chris Rolfe (Salesforce.org)     Initial Version
**/
public with sharing class AnimalActionRLClass2 {

    @AuraEnabled
    public static List<Animal_Action__c> getAnimalActions(String recId, String rTypeName){
       
    // System.debug('recId = ' + recId);
    // System.debug('rTypeName = ' + rTypeName);
       
       List<Animal_Action__c> animalActions= new List<Animal_Action__c>();
       
       
       boolean blnFirstTimeRound = false;
       for(RecordType rec : [SELECT Id FROM RecordType WHERE sObjectType = 'Animal_Action__c' and Name =:rTypeName])
       {
           if (!blnFirstTimeRound){
               List<Animal_Action__c> y = [SELECT Id, Name, Action_Completed__c
                                                      ,Date_Time_of_Action__c
                                                      ,Description__c
                                           FROM 	Animal_Action__c
                                           WHERE 	Animal__c= :recId and RecordTypeId= :rec.Id];
       for(Animal_Action__c z : y)
           {
           animalActions.add(z);
           }
       blnFirstTimeRound = true;     
       }    
        
   }
   return animalActions;
}
}