packaged/objects/Animal__c.object
<CustomObject>
    <description>[Animal Shelter Starter] The core object in the Animal Shelter Starter which stores the details about an animal.</description>
    <fields>
        <fullName>Animal_Name__c</fullName>
        <inlineHelpText>Name of the animal</inlineHelpText>
        <label>Name</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Arrival__c</fullName>
        <inlineHelpText>Date and time which the animal arrived at the shelter</inlineHelpText>
        <label>Date of Arrival</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>The type of animal e.g. Dog</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Animal_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Animal</label>
    <nameField>
        <displayFormat>ANIMAL{00000}</displayFormat>
        <label>Animal Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

packaged/globalValueSets/Animal_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Bird</fullName>
    </customValue>
    <customValue>
        <fullName>Cat</fullName>
    </customValue>
    <customValue>
        <fullName>Dog</fullName>
    </customValue>
    <customValue>
        <fullName>Donkey</fullName>
    </customValue>
    <customValue>
        <fullName>Horse</fullName>
    </customValue>
    <customValue>
        <fullName>Guinea Pig</fullName>
    </customValue>
    <customValue>
        <fullName>Hamster</fullName>
    </customValue>
    <customValue>
        <fullName>Hedgehog</fullName>
    </customValue>
    <customValue>
        <fullName>Ferret</fullName>
    </customValue>
    <customValue>
        <fullName>Gerbil</fullName>
    </customValue>
    <customValue>
        <fullName>Goat</fullName>
    </customValue>
    <customValue>
        <fullName>Mouse</fullName>
    </customValue>
    <customValue>
        <fullName>Pig</fullName>
    </customValue>
    <customValue>
        <fullName>Rabbit</fullName>
    </customValue>
    <customValue>
        <fullName>Pony</fullName>
    </customValue>
    <customValue>
        <fullName>Rat</fullName>
    </customValue>
    <customValue>
        <fullName>Reptile</fullName>
        <isActive>false</isActive>
        <label>Reptile</label>
    </customValue>
    <customValue>
        <fullName>Fish</fullName>
        <isActive>false</isActive>
        <label>Fish</label>
    </customValue>
    <description>Types of Animals</description>
    <masterLabel>Animal Type</masterLabel>
</GlobalValueSet>

packaged/classes/ProfilePictureControllerTest.cls
@isTest
public class ProfilePictureControllerTest {
    static testMethod void testMethod1 () {
        Animal__c TestAnimal = new Animal__c (Animal_Name__c='rex', Date_of_Arrival__c = date.today(), Type__c = 'Dog');
        insert TestAnimal;

        //Attachment TempAttachement = new Attachment();
        //TempAttachement = [SELECT Id, Name, LastModifiedDate, ContentType FROM Attachment WHERE parentid='a003z00000rlhSbAAI' AND ContentType IN ('image/png', 'image/jpeg', 'image/gif') ORDER BY LastModifiedDate DESC LIMIT 1];


        ProfilePictureController.saveAttachment(TestAnimal.id, 'Test File', '', 'image/jpeg');

        ProfilePictureController.getProfilePicture(TestAnimal.id);
    }
}