packaged/objects/Animal__c.object
<CustomObject>
    <description>[Animal Shelter Starter] The core object in the Animal Shelter Starter which stores the details about an animal.</description>
    <fields>
        <fullName>Animal_Name__c</fullName>
        <inlineHelpText>Name of the animal</inlineHelpText>
        <label>Name</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Breed__c</fullName>
        <inlineHelpText>Breed of Animal</inlineHelpText>
        <label>Breed</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Breed</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>The type of animal e.g. Dog</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Animal_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Animal</label>
    <nameField>
        <displayFormat>ANIMAL{00000}</displayFormat>
        <label>Animal Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Display_on_Map__c.field-meta.xml
<CustomField>
    <fullName>Display_on_Map__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box the display this animals location on the Animal Location map</inlineHelpText>
    <label>Display on Map</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Breed__c/Breed__c.object-meta.xml
<CustomObject>
    <description>[Animal Shelter Starter] - Contains list of animal breeds</description>
    <label>Breed</label>
    <nameField>
        <label>Breed Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Breeds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Breed__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>The animals type</inlineHelpText>
    <label>Type</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Animal_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bird</fullName>
    </customValue>
    <customValue>
        <fullName>Cat</fullName>
    </customValue>
    <customValue>
        <fullName>Dog</fullName>
    </customValue>
    <customValue>
        <fullName>Donkey</fullName>
    </customValue>
    <customValue>
        <fullName>Horse</fullName>
    </customValue>
    <customValue>
        <fullName>Guinea Pig</fullName>
    </customValue>
    <customValue>
        <fullName>Hamster</fullName>
    </customValue>
    <customValue>
        <fullName>Hedgehog</fullName>
    </customValue>
    <customValue>
        <fullName>Ferret</fullName>
    </customValue>
    <customValue>
        <fullName>Gerbil</fullName>
    </customValue>
    <customValue>
        <fullName>Goat</fullName>
    </customValue>
    <customValue>
        <fullName>Mouse</fullName>
    </customValue>
    <customValue>
        <fullName>Pig</fullName>
    </customValue>
    <customValue>
        <fullName>Rabbit</fullName>
    </customValue>
    <customValue>
        <fullName>Pony</fullName>
    </customValue>
    <customValue>
        <fullName>Rat</fullName>
    </customValue>
    <customValue>
        <fullName>Fish</fullName>
        <isActive>false</isActive>
        <label>Fish</label>
    </customValue>
    <customValue>
        <fullName>Reptile</fullName>
        <isActive>false</isActive>
        <label>Reptile</label>
    </customValue>
    <description>[Animal Shelter] Types of Animals - not used post version 1.12</description>
    <masterLabel>Animal Type (Legacy)</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Breed.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Affenpinscher</fullName>
    </customValue>
    <customValue>
        <fullName>Afghan Hound</fullName>
    </customValue>
    <customValue>
        <fullName>Airdale Terrier</fullName>
    </customValue>
    <customValue>
        <fullName>Akita</fullName>
    </customValue>
    <customValue>
        <fullName>Alaskan Malamute</fullName>
    </customValue>
    <customValue>
        <fullName>American Eskimo</fullName>
    </customValue>
    <customValue>
        <fullName>American Foxhound</fullName>
    </customValue>
    <customValue>
        <fullName>American Staffordshire Terrier</fullName>
    </customValue>
    <customValue>
        <fullName>American Water Spaniel</fullName>
    </customValue>
    <customValue>
        <fullName>Anatolian Sheepdog</fullName>
    </customValue>
    <customValue>
        <fullName>Australian Cattle Dog</fullName>
    </customValue>
    <customValue>
        <fullName>Australian Shepherd</fullName>
    </customValue>
    <customValue>
        <fullName>Australian Terrier</fullName>
    </customValue>
    <customValue>
        <fullName>Basenji</fullName>
    </customValue>
    <customValue>
        <fullName>Basset Hound</fullName>
    </customValue>
    <customValue>
        <fullName>Beagle</fullName>
    </customValue>
    <customValue>
        <fullName>Bearded Collie</fullName>
    </customValue>
    <customValue>
        <fullName>Beauceron</fullName>
    </customValue>
    <customValue>
        <fullName>Bedlington Terrier</fullName>
    </customValue>
    <customValue>
        <fullName>Belgian Malinois</fullName>
    </customValue>
    <customValue>
        <fullName>Belgian Sheepdog</fullName>
    </customValue>
    <customValue>
        <fullName>Belgian Tervuren</fullName>
    </customValue>
    <customValue>
        <fullName>Bernese Mountain Dog</fullName>
    </customValue>
    <customValue>
        <fullName>Bichon Frise</fullName>
    </customValue>
    <customValue>
        <fullName>Black And Tan Coonhound</fullName>
    </customValue>
    <customValue>
        <fullName>Black Russian Terrier</fullName>
    </customValue>
    <customValue>
        <fullName>Bloodhound</fullName>
    </customValue>
    <customValue>
        <fullName>Border Collie</fullName>
    </customValue>
    <customValue>
        <fullName>Border Terrier</fullName>
    </customValue>
    <customValue>
        <fullName>Borzoi</fullName>
    </customValue>
    <description>[Animal Shelter] Breed of Animal - Not used post version 1.12</description>
    <masterLabel>Breed (Legacy)</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AnimalLocation.cls
/**
 * @File Name          : AnimalLocation.apxc
 * @Description        : Gets animals that are to be displayed on Animal Location Map
 * @Author             : Chris Rolfe (Salesforce.org)
 * @Group              : 
 * @Last Modified By   : Chris Rolfe (Salesforce.org)
 * @Last Modified On   : 31/03/2021, 3:53:43 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    19/03/2021   Chris Rolfe (Salesforce.org)     Initial Version
 * 1.1    31/03/2021   Chris Rolfe (Salesforce.org)     Limit on SQOL Query set to 100
**/

public with sharing class AnimalLocation {
    @AuraEnabled

    public static List<Location>getAnimalLocation(){
       if(Schema.sObjectType.%%%NAMESPACED_ORG%%%Animal__c.isAccessible()){ 
            List<%%%NAMESPACED_ORG%%%Animal__c> animals = [SELECT Id, %%%NAMESPACED_ORG%%%Animal_Name__c, %%%NAMESPACED_ORG%%%Geolocation__latitude__s, %%%NAMESPACED_ORG%%%Geolocation__longitude__s, %%%NAMESPACED_ORG%%%Type__c, %%%NAMESPACED_ORG%%%Breed__c
                                        FROM %%%NAMESPACED_ORG%%%Animal__c
                                        WHERE %%%NAMESPACED_ORG%%%Display_on_Map__c = True
                                        ORDER BY CreatedDate DESC
                                        LIMIT 100];

            List<Location> loc = new List<Location>();
            for(%%%NAMESPACED_ORG%%%Animal__c anilocs :animals){
                GeoLocation geoInfo = new GeoLocation();
                geoInfo.Latitude = String.ValueOf(anilocs.%%%NAMESPACED_ORG%%%Geolocation__latitude__s);
                geoInfo.Longitude = String.ValueOf(anilocs.%%%NAMESPACED_ORG%%%Geolocation__longitude__s);
                Location locDetail = new Location();
                locDetail.icon = 'utility:animal_and_nature';
                locDetail.title = anilocs.%%%NAMESPACED_ORG%%%Animal_Name__c;
                locDetail.description = anilocs.%%%NAMESPACED_ORG%%%Type__c + ' ' + anilocs.%%%NAMESPACED_ORG%%%Breed__c;
                locDetail.location = geoInfo;

                loc.add(locDetail);
            }
            return loc;
        }
        System.debug('User does not have access to Animal Object. Please review access.');
        return null;


    }
    public class Location{
        @AuraEnabled
        public String icon{get;set;}
        @AuraEnabled
        public String title{get;set;}
        @AuraEnabled
        public String description{get;set;}
        @AuraEnabled
        public GeoLocation location{get;set;}
    }
    public class GeoLocation{
        @AuraEnabled
        public String Latitude{get;set;}
        @AuraEnabled
        public String Longitude{get;set;}
    }
}